"""grafana-setup (plan B): the six dashboards of spec 10.3 and a links dashboard per project.

Standard library only. The dashboards are the JSON files of ./dashboards (generated by
scripts/build_dashboards.py), downloaded and verified with this module by setup.py, which then
calls provision(). Import:
POST /api/dashboards/db with overwrite and a fixed UID, only when the normalised content differs:
Grafana increments `version` on every write, so it is never compared (spec 10.3).
"""

import hashlib
import json
from pathlib import Path

DIRECTORY = Path(__file__).resolve().parent / "dashboards"
# Closed list of spec 10.3, in display order: (uid, carries the project variable).
DASHBOARDS = (
    ("gc-project", True),
    ("gc-service", True),
    ("gc-frontend", True),
    ("gc-host", False),
    ("gc-pipeline", False),
    ("gc-cardinality", True),
)
# Fields Grafana adds or bumps on every write.
VOLATILE = ("id", "version")
MAX_UID = 40


class DashboardError(ValueError):
    """Missing or malformed dashboard file (reported by setup.py as a clean stop)."""


def short_uid(prefix, name):
    """prefix+name, or a truncated name plus 8 hex digits of its SHA-256 when over Grafana's 40 characters."""
    uid = prefix + name
    if len(uid) <= MAX_UID:
        return uid
    digest = hashlib.sha256(name.encode("utf-8")).hexdigest()[:8]
    return f"{prefix}{name[: MAX_UID - len(prefix) - 9]}-{digest}"


def load(directory=DIRECTORY):
    """The six dashboards, in the order of DASHBOARDS."""
    loaded = []
    for uid, _project in DASHBOARDS:
        path = Path(directory) / f"{uid}.json"
        try:
            item = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            raise DashboardError(f"{path.name}: {exc}") from None
        if item.get("uid") != uid:
            raise DashboardError(f"{path.name}: uid {item.get('uid')!r} != {uid!r}")
        loaded.append(item)
    return loaded


def normalize(item):
    return {key: value for key, value in item.items() if key not in VOLATILE}


def links_dashboard(project, dashboards):
    """Dashboard of a project folder: one link per dashboard, var-project already set (spec 10.3)."""
    with_project = dict(DASHBOARDS)
    links, lines = [], []
    for item in dashboards:
        url = f"/d/{item['uid']}" + (f"?var-project={project}" if with_project[item["uid"]] else "")
        links.append(
            {
                "type": "link",
                "title": item["title"],
                "url": url,
                "icon": "dashboard",
                "asDropdown": False,
                "includeVars": False,
                "keepTime": True,
                "targetBlank": False,
                "tags": [],
                "tooltip": item.get("description", ""),
            }
        )
        lines.append(f"- [{item['title']}]({url}) : {item.get('description', '')}")
    text = {
        "id": 1,
        "type": "text",
        "title": f"Tableaux de bord de {project}",
        "gridPos": {"x": 0, "y": 0, "w": 24, "h": 10},
        "options": {"mode": "markdown", "content": "\n".join(lines)},
    }
    return {
        "uid": short_uid("gcl-", project),
        "title": f"grafana-coolify — {project}",
        "tags": ["grafana-coolify"],
        "editable": True,
        "schemaVersion": 41,
        "time": {"from": "now-6h", "to": "now"},
        "templating": {"list": []},
        "annotations": {"list": []},
        "links": links,
        "panels": [text],
    }


def ensure_dashboard(api, dashboard, folder_uid):
    path = f"/api/dashboards/uid/{dashboard['uid']}"
    status, current = api.request("GET", path)
    if status == 200 and isinstance(current, dict):
        same_folder = (current.get("meta") or {}).get("folderUid") == folder_uid
        if same_folder and normalize(current.get("dashboard") or {}) == normalize(dashboard):
            return "unchanged"
        result = "updated"
    elif status == 404:
        result = "created"
    else:
        raise api.error("GET", path, status, current)
    body = {"dashboard": normalize(dashboard), "folderUid": folder_uid, "overwrite": True, "message": "grafana-setup"}
    api.expect("POST", "/api/dashboards/db", body)
    return result


def provision(api, projects, shared_folder_uid, folder_uid, out):
    """The six dashboards in the shared folder, then a links dashboard in each project folder."""
    boards = load()
    for board in boards:
        out(f"grafana-setup: dashboard {board['uid']}: {ensure_dashboard(api, board, shared_folder_uid)}")
    for project in projects:
        links = links_dashboard(project, boards)
        out(f"grafana-setup: dashboard {links['uid']}: {ensure_dashboard(api, links, folder_uid(project))}")
