import json
import sys
import unittest

from support import ROOT, promtool_check, run

sys.path.insert(0, str(ROOT / "scripts"))
import build_dashboards  # noqa: E402

DIRECTORY = ROOT / "config" / "grafana-setup" / "dashboards"
UIDS = ["gc-project", "gc-service", "gc-frontend", "gc-host", "gc-pipeline", "gc-cardinality"]
TITLES = ["Vue projet", "Erreurs et latence par service", "Frontend", "Hôte", "Santé du pipeline", "Cardinalité"]
# Values for the Grafana variables and macros, so that promtool can parse the queries.
SUBSTITUTIONS = {"$__rate_interval": "1m", "$project": "demo", "$env": "prod", "$service": "api", "$tenant": "acme"}


def targets(board):
    return [(panel["title"], target) for panel in board["panels"] for target in panel.get("targets", [])]


class BuildDashboardsTest(unittest.TestCase):
    """The closed list of spec 10.3, generated by scripts/build_dashboards.py and committed."""

    def setUp(self):
        self.boards = [json.loads((DIRECTORY / f"{uid}.json").read_text(encoding="utf-8")) for uid in UIDS]

    def test_committed_files_are_up_to_date(self):
        result = run([sys.executable, ROOT / "scripts" / "build_dashboards.py", "--check"])
        self.assertEqual(result.returncode, 0, result.stdout)

    def test_closed_list_of_six(self):
        self.assertEqual(sorted(p.name for p in DIRECTORY.glob("*.json")), sorted(f"{uid}.json" for uid in UIDS))
        self.assertEqual([b["uid"] for b in self.boards], UIDS)
        self.assertEqual([b["title"] for b in self.boards], TITLES)

    def test_every_query_uses_a_grafana_coolify_datasource(self):
        for board in self.boards:
            for title, target in targets(board):
                with self.subTest(dashboard=board["uid"], panel=title):
                    self.assertIn(target["datasource"]["uid"], ("gc-prometheus", "gc-loki"))

    def test_project_view_filters(self):
        self.assertEqual([v["name"] for v in self.boards[0]["templating"]["list"]], ["project", "env", "service", "tenant"])

    def test_service_variable_maps_to_the_label_of_each_store(self):
        """Spec 10.3: `service` in span-metrics, `job` in OTLP metrics, `service_name` in Loki."""
        exprs = [target["expr"] for board in self.boards for _title, target in targets(board)]
        for label in ('service=~"$service"', 'job=~"$service"', 'service_name=~"$service"'):
            with self.subTest(label=label):
                self.assertTrue(any(label in expr for expr in exprs), label)

    def test_project_variable_is_single_valued(self):
        for board in self.boards:
            for variable in board["templating"]["list"]:
                if variable["name"] == "project":
                    with self.subTest(dashboard=board["uid"]):
                        self.assertFalse(variable["multi"])
                        self.assertEqual(variable["allValue"], ".+")

    def test_promql_parses(self):
        exprs = []
        for board in self.boards:
            for title, target in targets(board):
                if target["datasource"]["uid"] == "gc-prometheus":
                    expr = target["expr"]
                    for name, value in SUBSTITUTIONS.items():
                        expr = expr.replace(name, value)
                    exprs.append((f"{board['uid']}: {title} {target['refId']}", expr))
        code, output = promtool_check(exprs)
        self.assertEqual(code, 0, output)

    def test_panels_do_not_overlap(self):
        for board in self.boards:
            cells = set()
            for panel in board["panels"]:
                grid = panel["gridPos"]
                area = {(x, y) for x in range(grid["x"], grid["x"] + grid["w"]) for y in range(grid["y"], grid["y"] + grid["h"])}
                with self.subTest(dashboard=board["uid"], panel=panel["title"]):
                    self.assertLessEqual(grid["x"] + grid["w"], 24)
                    self.assertFalse(cells & area)
                cells |= area

    def test_builder_is_deterministic(self):
        self.assertEqual(build_dashboards.build(), build_dashboards.build())


if __name__ == "__main__":
    unittest.main()
